language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
install:
  - composer self-update
  - composer install --no-interaction
script:
  - php vendor/bin/phpunit -c phpunit.xml
after_success:
  - php vendor/bin/coveralls -v
